from setuptools import setup, find_packages

setup(
    name="hearing_impaired_fmri_ai",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "torch>=2.0.0",
        "gymnasium>=0.26.0",
        "dreamerv3>=2.0.0",
        "numpy>=1.21.0",
        "soundfile>=0.12.1",
        "librosa>=0.10.0",
        "pydub>=0.25.1",
        "nilearn>=0.9.2",
        "nibabel>=4.0.0",
        "pandas>=1.5.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.12.0",
        "tqdm>=4.65.0",
        "scikit-learn>=1.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "black>=22.0.0",
            "flake8>=4.0.0",
            "jupyter>=1.0.0",
        ],
    },
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="Research project combining RL and fMRI for hearing-impaired learning",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/hearing_impaired_fmri_ai",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
) 